version: "3.9"

services:
  frontend:
    image: pankaj5000/frontend-image:latest
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend

  backend:
    image: pankaj5000/backend-image:latest
    ports:
      - 4000:4000
    restart: always
    environment:
      - mongo_url=mongodb+srv://japankaj282:pankaj7272@cluster0.ywkpfjr.mongodb.net/MERN_STACK_JOB_SEEKING?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=pankajpankajjakanp
    volumes:
      - ./backend/logs:/app/logs # Mount the logs directory

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.6
    ports:
      - 5044:5044
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.6
    user: root
    volumes:
      - ./backend/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./backend/logs:/app/logs
    depends_on:
      - logstash

volumes:
  elasticsearch-data: