# filebeat.yml
filebeat.inputs:
- type: log
  paths:
    - /home/pankaj/SPE_MajorProject/SPE-Major-Project/backend/app.log
  fields:
    log_type: application
  fields_under_root: true

#output.elasticsearch:
 # hosts: ["localhost:9200"]

setup.kibana:
  host: "localhost:5601"

output.logstash:
  hosts: ["logstash:5044"]
